# Generated by Django 2.0.4 on 2018-04-24 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
        ('bill_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(default=1, on_delete=True, related_name='has_bills', to='travel.User'),
            preserve_default=False,
        ),
    ]
