# Generated by Django 2.0.4 on 2018-04-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill_tracker', '0002_auto_20180424_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='desc',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
